### ISSUE TITLE
Feedback on Milestone #1

### ISSUE THREAD

**Issue by rainerlempert** [UBC-MDS/ColourblindR#14]
Good work team! Your package is set up and organized quite nicely. I noticed your Issue regarding implementing roxygen, thanks for clarifying that.  

The primary worry I have with your project is that you only have one test case that will be applied to all three of your functions. One of the primary goals of this milestone (and of the class!) is to experiment and become familiar with different types of tests. Is there a way that you could implement a greater variety of tests to your functions? Perhaps this will become clearer once you start to write the functions. 

You also don't include any tests for checking the inputs and outputs of your functions. I understand that this might not completely applicable, since your functions are just themes, but you could at least check to see if what you are creating is compatible with different types of ggplot2/matplotlib objects.

**Comment by sabrinatkk** [comment]
Hi @rainerlempert, 

thank you for your feedback when we are addressing your suggestions. Can you clarify what kind of tests you are suggesting by "different types of tests"?  In the last milestone, we tested almost all aspects of a graph should have from font size, background colour, object colour and sizes and more.

Your guidance is much appreciated!

Sabrina

**Comment by rainerlempert** [comment]
Hi @sabrinatkk 

The issue is that you only created one script to test all three of your functions. Your functions will do different things, namely create plots with different colors palettes. You should have three tests that make sure the outputted colors of your plots adhere to the palettes described in your readme.

Looking at your python package, it looks like you are changing your functions, which is fine! Let's have a conversation at lab next Tuesday about the direction of this project, just to make sure we are all on the same page.
