### ISSUE TITLE
Vignette

### ISSUE THREAD

**Issue by sabrinatkk** [UBC-MDS/ColourblindR#49]
Hi @rainerlempert , 

I would like to bring this to your attention. The vignette folder in the Milestone 3 release we published only contained .rmd file. Even though our vignette was knitted perfectly fine, our vignette wasn't called via "vignette()" or browseVignettes()". So I removed the [pdf ](https://github.com/UBC-MDS/ColourblindR/blob/master/vignettes/colourblindr.pdf) and HTML files in an attempt to solve the issue. 

This issue is opened so that you are aware of that. And feel free to click on the link above to check out the vignette of our package. 

Thank you!

@sabrinatkk

**Comment by rainerlempert** [comment]
Thanks for letting me know @sabrinatkk !
