### ISSUE TITLE
Milestone #3 Feedback

### ISSUE THREAD

**Issue by rainerlempert** [UBC-MDS/ColourblindR#56]
Great work team! Your package installs seamlessly, your functions work well, and all of your tests pass. Your functions all have good documentation (including examples) and your README is well maintained. You've clearly put a lot of work into this project! Two small couple comments:
- Regarding your issue getting `browseVignettes()` to work, maybe [this thread](https://github.com/STAT545-UBC/Discussion/issues/68) may be of some help? If not we can try to troubleshoot during lab.
- I reran `pytest` on the new version of Colourblind8 and encountered the same error on `test_histogram`. It would be good to try and fix that for the final project.

**Comment by ian-flores** [comment]
@hfboyce was this addressed? Or do we still got to do it?

**Comment by hfboyce** [comment]
All addressed @ian-flores and mentioned personally to Rainer.
