### ISSUE TITLE
Feedback on Project Proposal

### ISSUE THREAD

**Issue by rainerlempert** [UBC-MDS/ColourblindR#6]
See feedback [here](https://github.com/UBC-MDS/Colourblind8/issues/9).  
My comments here are much the same (obviously!). Do you intend to make this compatible with `ggplot2`? Just base R graphing? Other graphing packages?

**Comment by sabrinatkk** [comment]
Hi  @rainerlempert , 

We have provided a [general response](https://github.com/UBC-MDS/Colourblind8/issues/9#issuecomment-462021352) that is applicable to both [Colourblind8 ](https://github.com/UBC-MDS/Colourblind8) and [ColourblindR](https://github.com/UBC-MDS/ColourblindR).

Yes, we intend to make ColourblindR compatible with `ggplot2` at this stage, please see our [scope](https://github.com/UBC-MDS/ColourblindR#Scope)
