### ISSUE TITLE
NEW hex

### ISSUE THREAD

**Issue by hfboyce** [UBC-MDS/ColourblindR#77]
Added a moving hex sticker! I didn't want to clone so I made a bunch of patches don't yell at me. 
I also want to update the docs html file with it but didn't get around to it because i didn't want to update both the rmd and reknit for the html. 
.... BUT HEY ISN'T SHE PRETTY?!! 
She looks like [this](https://github.com/hfboyce/ColourblindR)

**Comment by ian-flores** [comment]
It looks nice. That was the PR I merged right?

**Comment by hfboyce** [comment]
Yup!
